export const CREATE_USER = "CREATE_USER";
export const CREATE_CARD = "CREATE_CARD";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const RETRIEVE_PROFILECARDS = "RETRIEVE_PROFILECARDS";
export const RETRIEVE_PROFILETRANSACTIONS = "RETRIEVE_PROFILETRANSACTIONS";